name: .NET Deploy

on:
  push:
    branches: [ "production" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Publish
      run: dotnet publish -c Release --no-restore

    - name: Upload build
      uses: actions/upload-artifact@v4
      id: build-artifact
      with:
        name: build
        path: BanchoMultiplayerBot.Web/bin/Release/net9.0/publish/wwwroot

    - name: Deploy build
      run: |
        curl \
        --silent \
        --request POST \
        --url ${{ secrets.DEPLOY_TARGET }} \
        --header 'Content-Type: application/json' \
        --data '{ "DeployKey": "${{ secrets.DEPLOY_KEY }}", "ArtifactId": ${{ steps.build-artifact.outputs.artifact-id }} }'
